version: '3.8'
services:

  api-service:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    command: go run main.go -b 0.0.0.0

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local

